Ansible 1
Otus-DevOps-2021-05/danoque_infra pull request #14
Opened 2021-09-08 16:27 UTC by danoque

# Выполнено ДЗ №

 - [v ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
1. С помощью Terraform и заготовленного образа Packer в облаке развёрнуто 2 виртуальных машины: appserver и dbserver.
2.С помощью файла inventory.yml  осуществляется подключение к хостам по их адресам.
3. В файле ansible.cfg были описаны параметры подключения к хостам такие как: имя пользователя и путь к приватному ключу.
4. На различных командах и модулях была протестирована работа ansible по конфигурированию удалённых хостов,был составлен плейбук для клонирования репозитория. Было произведено сравнение работы модуля Command и Shell, из чего был сделан вывод о том, что модуль command выполняет команды не используя оболочку.
5.После выполнения команды "ansible app -m command -a 'rm -rf ~/reddit'" выполнение плейбука снова происходит успешно и вызывает изменения на целевом хосте, так как данные были удалены.

## Как запустить проект:
 - Например, запустить команду ansible -m ping -i inventory.yml в директории ansible

## Как проверить работоспособность:
 - Например, перейти по ссылке 178.154.202.94

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-09-09 15:46 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил комментарий к файлу. ДЗ вовзращаю на доработку =)

2021-09-09 15:46 UTC, mrgreyves commented on ansible/inventory
> +appserver ansible_host=35.195.74.54
В инвентарь надо добавить группы для app и db =)

2021-09-09 17:53 UTC, danoque commented on ansible/inventory
> +appserver ansible_host=35.195.74.54
Помогите, пожалуйста! Тест единственное на что ругается - это на синтаксис clone.yml. А инвентори там два, потому что когда он был один правильный со всеми группами для апп и дб, то тесты ругались на отсутсвие старой версии инвентори.

2021-09-09 18:00 UTC, danoque commented on ansible/inventory
> +appserver ansible_host=35.195.74.54
> В инвентарь надо добавить группы для app и db =)

Как?!? Как это работает? Ведь ругался он на синтакс-чек файла clone.yml =(

2021-09-09 18:02 UTC, danoque commented on ansible/inventory
> +appserver ansible_host=35.195.74.54
> В инвентарь надо добавить группы для app и db =)

Хорошо, что послушался Вас и нашёл этот момент в описании дз, но когда опаздываешь и отстаёшь по выполнению дз, такие моменты в тестах это конечно подстава)

2021-09-11 13:58 UTC, danoque reviewed
All changes have been made

2021-09-11 15:32 UTC, mrgreyves commented on ansible/inventory
> +appserver ansible_host=35.195.74.54
Если память не изменяет, то как раз таки чек не смог найти целевые инстансы из-за проблемы в инвентаре. Отсюда собственно и ошибка =)

2021-09-11 15:32 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-09-11 15:55 UTC, merged